fix: MVP 임시 통합 - 이후 리팩토링 예정
<type>([scope]): <commit message>

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,19 +1,24 @@
-##!/bin/sh
-#
-#echo "🔍 Running pre-commit hook..."
-#
-## 테스트 실행 (선택)
-#./gradlew test
-#if [ $? -ne 0 ]; then
-#    echo "❌ Tests failed! Fix the issues before committing."
-#    exit 1
-#fi
-#
-#./gradlew spotlessApply build
-#if [ $? -ne 0 ]; then
-#    echo "❌ Checkstyle failed! Fix the issues before committing."
-#    exit 1
-#fi
-#
-#echo "✅ pre-commit checks passed!"
-#exit 0
+#!/bin/sh
+
+echo "🔍 Running pre-commit hook..."
+
+# 테스트 실행
+./gradlew test || {
+    printf "\e[31m❌ Tests failed! Fix the issues before committing.\e[0m\n";
+    exit 1;
+}
+
+# 코드 스타일 검사 (자동 수정 없음)
+./gradlew spotlessCheck || {
+    printf "\e[31m❌ Spotless check failed! './gradlew spotlessApply'명령어를 실행하고 sptless가 적용된 파일들을 다시 add 후 commit해주세요.\e[0m\n";
+    exit 1;
+}
+
+# 프로젝트 빌드 수행
+./gradlew build || {
+    printf "\e[31m❌ Build failed! Fix the issues before committing.\e[0m\n";
+    exit 1;
+}
+
+printf "\e[32m✅ pre-commit checks passed!\e[0m\n"
+exit 0
diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,13 +1,13 @@
-##!/bin/sh
-#
-#echo "🚀 Running pre-push hook..."
-#
-## 빌드 및 테스트 실행
-#./gradlew build
-#if [ $? -ne 0 ]; then
-#    echo "❌ Build or tests failed! Push rejected."
-#    exit 1
-#fi
-#
-#echo "✅ pre-push checks passed!"
-#exit 0
+#!/bin/sh
+
+echo "🚀 Running pre-push hook..."
+
+# 빌드 및 테스트 실행
+./gradlew build
+if [ $? -ne 0 ]; then
+    echo "❌ Build or tests failed! Push rejected."
+    exit 1
+fi
+
+echo "✅ pre-push checks passed!"
+exit 0
